version: '3.7'
services:
    mysql_agenda_db:
        container_name: mysql_agenda
        image: mysql
        ports:
            -   3306:3306
        volumes: 
            -   mysql_vol:/var/lib/mysql
        networks:
            -   app_net
        environment:
            -   MYSQL_ROOT_PASSWORD=123456
            -   MYSQL_DATABASE=agenda
            -   MYSQL_USER=localagenda
            -   MYSQL_PASSWORD=123456

    app:
        container_name: agenda-app
        build:  ./backend
        ports: 
            -   "4000:4000"
        depends_on: 
            -   mysql_agenda_db
        networks:
            app_net:
        env_file:
            -   ./backend/.env
            -   ./backend/.env.production
        image:  agenda-app

volumes:
    mysql_vol:

networks:
    app_net:
        driver: bridge